apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ex288-php-mysql
  labels:
    template: php-app
  annotations:
    description: >
      This template deploys a PHP application with a MySQL database.
    tags: php,mysql,quickstart
parameters:
  - name: APPLICATION_DOMAIN
    description: >
      The domain name of the application. Used to set the hostname for the route.
    required: true
  - name: HELLO_AUDIENCE
    description: The audience to greet.
    value: Engineers
  - name: PHP_VERSION
    description: Version of PHP to use.
    value: "8.0"
  - name: MYSQL_VERSION
    description: Version of MySQL to use.
    value: "8.0"
  - name: GIT_REPOSITORY_URL
    description: The Git repository URL for the application.
    value: "http://git.test.example.com/work/php-app.git"
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: php-app
      labels:
        app: php-app
    spec:
      ports:
        - port: 8080
          targetPort: 8080
      selector:
        app: php-app
  - apiVersion: v1
    kind: Route
    metadata:
      name: php-app
      labels:
        app: php-app
    spec:
      host: "${APPLICATION_DOMAIN}"
      to:
        kind: Service
        name: php-app
      port:
        targetPort: 8080
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: php-app
      labels:
        app: php-app
        template: php-app
    spec:
      replicas: 1
      selector:
        app: php-app
      template:
        metadata:
          labels:
            app: php-app
        spec:
          containers:
            - name: php
              image: "php:${PHP_VERSION}"
              ports:
                - containerPort: 8080
              env:
                - name: HELLO_AUDIENCE
                  value: "${HELLO_AUDIENCE}"
                - name: MYSQL_SERVICE_HOST
                  value: mysql
                - name: GIT_REPOSITORY_URL
                  value: "${GIT_REPOSITORY_URL}"
              readinessProbe:
                httpGet:
                  path: /
                  port: 8080
                initialDelaySeconds: 5
                timeoutSeconds: 3
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: mysql
      labels:
        app: mysql
        template: php-app
    spec:
      replicas: 1
      selector:
        app: mysql
      template:
        metadata:
          labels:
            app: mysql
        spec:
          containers:
            - name: mysql
              image: "mysql:${MYSQL_VERSION}"
              ports:
                - containerPort: 3306
              env:
                - name: MYSQL_USER
                  value: user
                - name: MYSQL_PASSWORD
                  value: password
                - name: MYSQL_DATABASE
                  value: sampledb
                - name: MYSQL_ROOT_PASSWORD
                  value: rootpassword
  - apiVersion: v1
    kind: Service
    metadata:
      name: mysql
      labels:
        app: mysql
    spec:
      ports:
        - port: 3306
          targetPort: 3306
      selector:
        app: mysql
