apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: mysql-ephemeral-ejercicio
  annotations:
    description: >
      Plantilla para desplegar una base de datos MySQL sin almacenamiento persistente.
      Completa las secciones pendientes como parte del ejercicio.
    tags: database,mysql
parameters:
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Cantidad máxima de memoria que puede usar el contenedor.
    value: 512Mi
  - name: DATABASE_SERVICE_NAME
    displayName: Database Service Name
    description: Nombre del servicio de la base de datos.
    value: mysql
  - name: MYSQL_USER
    displayName: MySQL User
    description: Usuario para conectarse a la base de datos.
    value: user
  - name: MYSQL_PASSWORD
    displayName: MySQL Password
    description: Contraseña para el usuario MySQL.
    value: password
  - name: MYSQL_DATABASE
    displayName: MySQL Database
    description: Nombre de la base de datos MySQL.
    value: sampledb
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: "${DATABASE_SERVICE_NAME}-secret"
    stringData:
      database-user: "${MYSQL_USER}"
      database-password: "${MYSQL_PASSWORD}"
      database-name: "${MYSQL_DATABASE}"
  - apiVersion: v1
    kind: Service
    metadata:
      name: "${DATABASE_SERVICE_NAME}"
    spec:
      ports:
        - name: mysql
          port: 3306
          targetPort: 3306
      selector:
        name: "${DATABASE_SERVICE_NAME}"
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      name: "${DATABASE_SERVICE_NAME}"
    spec:
      # Completa aquí los detalles del DeploymentConfig
      # Por ejemplo: contenedores, imagen, probes, etc.
