apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ejercicio-mysql-template
  annotations:
    description: >
      Plantilla básica para desplegar MySQL sin almacenamiento persistente.
      Completa los parámetros y objetos necesarios para que sea funcional.
    tags: database,mysql
parameters:
  - name: MEMORY_LIMIT
    displayName: Memory Limit
    description: Cantidad máxima de memoria que puede usar el contenedor.
    value: 512Mi
  - name: DATABASE_SERVICE_NAME
    displayName: Database Service Name
    description: Nombre del servicio de la base de datos.
    value: mysql-ejemplo
  - name: MYSQL_USER
    displayName: MySQL User
    description: Usuario para conectarse a la base de datos.
    required: true
  - name: MYSQL_PASSWORD
    displayName: MySQL Password
    description: Contraseña para el usuario MySQL.
    required: true
  - name: MYSQL_DATABASE
    displayName: MySQL Database
    description: Nombre de la base de datos MySQL.
    required: true
objects:
  # Añade aquí los objetos necesarios: Secret, Service y DeploymentConfig
  # Solo dejamos un borrador del Secret como ejemplo.
  - apiVersion: v1
    kind: Secret
    metadata:
      name: "${DATABASE_SERVICE_NAME}-secret"
    stringData:
      mysql-user: "${MYSQL_USER}"
      mysql-password: "${MYSQL_PASSWORD}"
      mysql-database: "${MYSQL_DATABASE}"
  # Aquí puedes añadir el resto de los objetos como Service, DeploymentConfig, etc.
